"""
DBProj1-master - Flask Application
Auto-generated by FrameShift
"""

from flask import Flask
from extensions import db, migrate, admin

def create_app(config_name='development'):
    """Application factory pattern"""
    app = Flask(__name__)

    # Load configuration
    from config import config
    app.config.from_object(config[config_name])

    # Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    admin.init_app(app)


    # Register blueprints
    from DBApp.routes import DBApp_bp
    from DBProj1.routes import DBProj1_bp
    app.register_blueprint(DBApp_bp, url_prefix='/DBApp')
    app.register_blueprint(DBProj1_bp, url_prefix='/DBProj1')

    # Import models to ensure they're registered with SQLAlchemy
    import DBApp.models  # Ensure SQLAlchemy model registration

    # Register Flask-Admin Views
    try:
        from DBApp.admin_views import init_admin_views
        init_admin_views(admin)
    except ImportError:
        pass
    try:
        from DBProj1.admin_views import init_admin_views
        init_admin_views(admin)
    except ImportError:
        pass

    # Create database tables
    with app.app_context():
        db.create_all()

    @app.route('/')
    def index():
        return "Welcome to DBProj1-master!"

    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True, host='0.0.0.0', port=5000)
