"""
app - Flask Application
Auto-generated by FrameShift
"""

from flask import Flask
from extensions import db, migrate

def create_app(config_name='development'):
    """Application factory pattern"""
    app = Flask(__name__)

    # Load configuration
    from config import config
    app.config.from_object(config[config_name])

    # Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)


    # Register blueprints
    # No blueprints found
    # No blueprints to register

    # Import models to ensure they're registered with SQLAlchemy
    # No models found

    # Create database tables
    with app.app_context():
        db.create_all()

    @app.route('/')
    def index():
        return "Welcome to app!"

    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True, host='0.0.0.0', port=5000)
