"""
simple-django-project-master - Flask Application
Auto-generated by FrameShift
"""

from flask import Flask
from extensions import db, migrate

def create_app(config_name='development'):
    """Application factory pattern"""
    app = Flask(__name__)

    # Load configuration
    from config import config
    app.config.from_object(config[config_name])

    # Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)


    # Register blueprints
    from panorbit.routes import panorbit_bp
    from static.routes import static_bp
    from templates.routes import templates_bp
    from world.routes import world_bp
    app.register_blueprint(panorbit_bp, url_prefix='/panorbit')
    app.register_blueprint(static_bp, url_prefix='/static')
    app.register_blueprint(templates_bp, url_prefix='/templates')
    app.register_blueprint(world_bp, url_prefix='/world')

    # Import models to ensure they're registered with SQLAlchemy
    # No models found

    # Create database tables
    with app.app_context():
        db.create_all()

    @app.route('/')
    def index():
        return "Welcome to simple-django-project-master!"

    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True, host='0.0.0.0', port=5000)
